name: Build Crystal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            build_cmd: build:mac:universal
            artifact_name: crystal-macos
            artifact_path: dist-electron/*.dmg
          - os: ubuntu-latest
            build_cmd: build:linux:ci
            artifact_name: crystal-linux
            artifact_path: |
              dist-electron/*.deb
              dist-electron/*.AppImage
              dist-electron/*.snap
              dist-electron/*.flatpak
    
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: read  # Required for accessing repository contents

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.15.1'
        cache: 'pnpm'

    # Cache native modules and electron binaries to speed up rebuilds
    - name: Cache native modules
      uses: actions/cache@v4
      with:
        path: |
          main/node_modules/.bin
          main/build
          ~/.electron
          ~/.electron-gyp
        key: ${{ runner.os }}-native-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-native-modules-

    - name: Cache Electron binaries
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/electron
          ~/.cache/electron-builder
        key: ${{ runner.os }}-electron-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-electron-

    - name: Install dependencies
      run: pnpm install

    # Build frontend and main process in parallel for faster builds
    - name: Build frontend and main process
      run: |
        # Build both frontend and main process concurrently
        pnpm run build:frontend &
        pnpm run build:main &
        wait

    - name: Rebuild native modules
      run: pnpm run electron:rebuild

    - name: Generate NOTICES file
      run: pnpm run generate-notices

    - name: Build application
      run: pnpm run ${{ matrix.build_cmd }}
      env:
        # GitHub token (required by electron-builder even for non-publish builds)
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # macOS code signing (optional for CI builds)
        CSC_LINK: ${{ matrix.os == 'macos-latest' && secrets.APPLE_CERTIFICATE || '' }}
        CSC_KEY_PASSWORD: ${{ matrix.os == 'macos-latest' && secrets.APPLE_CERTIFICATE_PASSWORD || '' }}
        # macOS notarization (optional for CI builds)
        APPLE_ID: ${{ matrix.os == 'macos-latest' && secrets.APPLE_ID || '' }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ matrix.os == 'macos-latest' && secrets.APPLE_APP_PASSWORD || '' }}
        APPLE_TEAM_ID: ${{ matrix.os == 'macos-latest' && secrets.APPLE_TEAM_ID || '' }}
        # Only enable signing when certificates are available
        CSC_IDENTITY_AUTO_DISCOVERY: ${{ matrix.os == 'macos-latest' && 'true' || 'false' }}

    - name: List build artifacts
      run: ls -la dist-electron/

    # Cache Flatpak runtime and dependencies to speed up builds
    - name: Cache Flatpak runtime
      if: matrix.os == 'ubuntu-latest'
      uses: actions/cache@v4
      with:
        path: |
          /var/lib/flatpak
          ~/.local/share/flatpak
        key: ${{ runner.os }}-flatpak-runtime-v1
        restore-keys: |
          ${{ runner.os }}-flatpak-runtime-

    - name: Build Flatpak
      if: matrix.os == 'ubuntu-latest'
      run: |
        # Install flatpak-builder with minimal package update
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends flatpak flatpak-builder
        
        # Add flathub repository
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        
        # Install required runtime and SDK (cached between runs)
        sudo flatpak install -y --noninteractive flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08 org.electronjs.Electron2.BaseApp//23.08 || true
        
        # Find the actual AppImage file
        echo "Looking for AppImage files..."
        ls -la dist-electron/*.AppImage || true
        
        # Get the AppImage path (handle different naming patterns)
        APPIMAGE=$(ls dist-electron/*.AppImage 2>/dev/null | head -n1)
        if [ -z "$APPIMAGE" ]; then
          echo "Error: No AppImage found in dist-electron/"
          exit 1
        fi
        echo "Found AppImage: $APPIMAGE"
        
        # Update manifest with actual AppImage path
        sed -i "s|path: dist-electron/Crystal-\*.AppImage|path: $APPIMAGE|" com.stravu.crystal.yml
        
        # Build Flatpak with ccache for faster rebuilds
        flatpak-builder --force-clean --repo=repo --ccache build-dir com.stravu.crystal.yml
        
        # Create bundle
        flatpak build-bundle repo dist-electron/crystal.flatpak com.stravu.crystal
        
        # List artifacts again to confirm
        ls -la dist-electron/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_path }}
        if-no-files-found: error
        retention-days: 7

